# Generated by Django 4.1.4 on 2023-03-31 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Reservation", "0007_alter_hostel_hostel_image"),
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_academic_year",
                    models.DateField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="start_academic_year",
                    ),
                ),
                (
                    "end_academic_year",
                    models.DateField(
                        blank=True, null=True, verbose_name="end_academic_year"
                    ),
                ),
                (
                    "date_booked",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date_booked"
                    ),
                ),
                (
                    "price",
                    models.FloatField(default=0.0, max_length=50, verbose_name="price"),
                ),
                (
                    "payment",
                    models.BooleanField(
                        default=False, max_length=50, verbose_name="payment"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room",
                        to="Reservation.room",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to="Authentication.student",
                    ),
                ),
            ],
        ),
    ]
