# Generated by Django 4.1.4 on 2022-12-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=13, unique=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.IntegerField(unique=True, verbose_name='phone number')),
                ('faculty', models.CharField(max_length=50, verbose_name='faculty')),
                ('program', models.CharField(max_length=50, verbose_name='program')),
            ],
        ),
    ]
