# Generated by Django 4.1.4 on 2022-12-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Authentication.position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(default='Student', max_length=300, verbose_name='Name of position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(verbose_name='phone_number'),
        ),
    ]
