# Generated by Django 4.1.4 on 2022-12-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_student_user_user_username_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
