# Generated by Django 4.1.4 on 2022-12-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
