# Generated by Django 4.1.4 on 2022-12-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_remove_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
    ]
