# Generated by Django 4.1.4 on 2023-01-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='room',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='block',
        ),
        migrations.AddField(
            model_name='block',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_in_school', to='Reservation.hostel'),
        ),
        migrations.AddField(
            model_name='floor',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_in_hostel', to='Reservation.block'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_in_block', to='Reservation.floor'),
        ),
    ]
