# Generated by Django 4.1.4 on 2023-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reservation", "0002_remove_block_floor_remove_floor_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="floor",
            name="gender",
            field=models.CharField(
                default="Mixed", max_length=50, verbose_name="gender"
            ),
        ),
        migrations.AddField(
            model_name="hostel",
            name="hostel_type",
            field=models.CharField(
                default="Campus Hostel", max_length=50, verbose_name="hostel type"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="is_available",
            field=models.CharField(
                default=False, max_length=50, verbose_name="is available"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="number_of_persons",
            field=models.IntegerField(default=0, verbose_name="number of persons"),
        ),
        migrations.AddField(
            model_name="room",
            name="price",
            field=models.FloatField(default=0.0, max_length=50, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="block",
            name="name",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Name of block"
            ),
        ),
        migrations.AlterField(
            model_name="floor",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Name of floor"),
        ),
        migrations.AlterField(
            model_name="hostel",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Name of hostel"),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Name of room"),
        ),
    ]
