# Generated by Django 4.1.4 on 2023-02-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Reservation",
            "0003_floor_gender_hostel_hostel_type_room_is_available_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Name of block"),
        ),
    ]
