# Generated by Django 4.1.4 on 2023-02-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reservation", "0004_alter_block_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="hostel_image",
            field=models.ImageField(
                default="hostel.png",
                max_length=50,
                upload_to="",
                verbose_name="hostel image",
            ),
        ),
    ]
