# Generated by Django 4.1.4 on 2023-02-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reservation", "0005_hostel_hostel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="contact",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="contact"
            ),
        ),
        migrations.AlterField(
            model_name="hostel",
            name="hostel_image",
            field=models.ImageField(
                max_length=50, upload_to="", verbose_name="hostel image"
            ),
        ),
    ]
