# Generated by Django 4.1.4 on 2023-03-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reservation", "0006_hostel_contact_alter_hostel_hostel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="hostel_image",
            field=models.ImageField(
                upload_to="hostel_images/", verbose_name="hostel image"
            ),
        ),
    ]
