# Generated by Django 4.1.4 on 2023-07-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Reservation", "0007_alter_hostel_hostel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="contact",
            field=models.CharField(blank=True, max_length=20, verbose_name="contact"),
        ),
    ]
